# Generated by Django 4.2.3 on 2023-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0002_remove_vehicle_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_driver_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
