# Generated by Django 4.2.3 on 2023-07-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0003_vehicle_vehicle_driver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_driver_name',
            new_name='vehicle_driver',
        ),
    ]
