# Generated by Django 4.2.3 on 2023-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0004_rename_vehicle_driver_name_vehicle_vehicle_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyl_rec', models.IntegerField()),
                ('cyl_ret', models.IntegerField()),
                ('cyl_full', models.IntegerField()),
                ('cyl_empty', models.IntegerField()),
                ('cyl_defective', models.IntegerField()),
                ('cyl_delivered', models.IntegerField()),
                ('cyl_received', models.IntegerField()),
                ('total_cylinder', models.IntegerField()),
            ],
        ),
    ]
