# Generated by Django 4.2.3 on 2023-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0005_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('del_amt', models.IntegerField()),
                ('del_pay_mode', models.CharField(choices=[('CSH', 'Cash'), ('ONL', 'Online'), ('UPI', 'UPI Payment')], max_length=3)),
            ],
        ),
    ]
